=== cnabio/cnab-spec/schema/bundle.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://cnab.io/v1/bundle.schema.json",
    "title": "CNAB1 Bundle Descriptor",
    "description": "Cloud Native Application - Core version 1 - Bundle Descriptor",
    "type": "object",
    "properties": {
        "schemaVersion": {
            "description": "The version of the CNAB specification. This should always be the string 'v1' for this schema version.",
            "type": "string"
        },
        "name":{
            "description": "The name of this bundle",
            "type": "string"
        },
        "version":{
            "description": "A SemVer2 version for this bundle",
            "type": "string",
            "pattern": "v?([0-9]+)(\\.[0-9]+)?(\\.[0-9]+)?(-([0-9A-Za-z\\-]+(\\.[0-9A-Za-z\\-]+)*))?(\\+([0-9A-Za-z\\-]+(\\.[0-9A-Za-z\\-]+)*))?"
        },
        "description":{
            "description": "A description of this bundle, intended for users",
            "type": "string"
        },
        "keywords":{
            "description": "A list of keywords describing the bundle, intended for users",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "maintainers":{
            "description": "A list of parties responsible for this bundle, with contact info",
            "type": "array",
            "items": {
                "description": "An object that describes a maintainer",
                "type": "object",
                "properties": {
                    "name": {
                        "description": "Name of party reponsible for this bundle",
                        "type": "string"
                    },
                    "email":{
                        "description": "Email address of responsible party",
                        "type": "string"
                    },
                    "url":{
                        "description": "URL of the responsible party, perhaps containing additional contact info",
                        "type": "string"
                    }
                },
                "required": ["name"]
            }
        },
        "license":{
            "description": "The SPDX license code or proprietary license name for this bundle",
            "type": "string"
        },
        "invocationImages":{
            "description": "The array of invocation image definitions for this bundle",
            "type": "array",
            "items": {
                "$ref": "#/definitions/invocationImage"
            }
        },
        "images":{
            "description": "Images that are used by this bundle",
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/image"
            }
        },
        "credentials":{
            "description":"Credentials to be injected into the invocation image",
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/credential"
            }
        },
        "actions":{
            "description": "Custom actions that can be triggered on this bundle, action name should be namespaced and use reverse DNS notation",
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "modifies": {
                        "description": "Must be set to true if the action can change any resource managed by this bundle",
                        "type": "boolean"
                    },
                    "description": {
                        "description": "A description of the purpose of this action",
                        "type": "string"
                    },
                    "stateless":{
                        "description": "Indicates that the action is purely informational, that credentials are not required, and that the runtime should not keep track of its invocation",
                        "type": "boolean",
                        "default": "false"
                    }
                }
            }
        },
        "custom":{
            "$comment": "reserved for custom extensions"
        },
        "parameters":{
            "description": "Parameters that can be injected into the invocation image",
            "type": "object",
            "properties": {
                "fields" : {
                    "type": "object",
                    "additionalProperties": {
                        "allOf": [
                            { "$ref":  "#/definitions/parameter" },
                            { "$ref":  "http://json-schema.org/draft-07/schema#" }
                        ]
                    }
                },
                "required": { "$ref": "http://json-schema.org/draft-07/schema#/properties/required" }
            }
           
        },
        "outputs":{
            "description": "Values that are produced by executing the invocation image",
            "type": "object",
            "properties": {
                "required": { "$ref": "http://json-schema.org/draft-07/schema#/properties/required" }
            },
            "additionalProperties": {
                "allOf": [
                    { "$ref":  "#/definitions/output" },
                    { "$ref":  "http://json-schema.org/draft-07/schema#" }
                ]
            }
        }
    },
    "required": [ "name", "version", "invocationImages", "schemaVersion"],
    "definitions": {
        "invocationImage": {
            "description": "A bootstrapping image for the CNAB bundle.",
            "type": "object",
            "properties": {
                "image":{
                    "description": "A resolvable reference to the image. This may be interpreted differently based on imageType, but the default is to treat this as an OCI image",
                    "type": "string"
                },
                "originalImage":{
                    "description": "A resolvable reference to the original image. This may be interpreted differently based on imageType, but the default is to treat this as an OCI image. If this is not specified, the value is assumed to be that of the image field",
                    "type": "string"
                },
                "imageType":{
                    "description": "The type of image. If this is not specified, 'oci' is assumed",
                    "type": "string",
                    "default": "oci"
                },
                "digest":{
                    "description": "A cryptographic hash digest that can be used to validate the image. This may be interpreted differently based on imageType",
                    "type": "string"
                },
                "size": {
                    "description": "The image size in bytes",
                    "type":"integer"
                },
                "platform":{
                    "description": "The target platform",
                    "type": "object",
                    "properties": {
                        "architecture": {
                            "description": "The architecture of the image (i386, amd64, arm32, arm64,...)",
                            "type": "string"
                        },
                        "os": {
                            "description": "The operating system of the image (linux, windows, darwin,...)",
                            "type": "string"
                        }
                    }
                },
                "mediaType":{
                    "description": "The media type of the image",
                    "type": "string"
                }
            },
            "required": ["image"]
        },
        "image": {
            "description": "An application image for this CNAB bundle",
            "type": "object",
            "properties": {
                "description": {
                    "description": "A description of the purpose of this image",
                    "type": "string"
                },
                "image":{
                    "description": "A resolvable reference to the image. This may be interpreted differently based on imageType, but the default is to treat this as an OCI image",
                    "type": "string"
                },
                "originalImage":{
                    "description": "A resolvable reference to the image. This may be interpreted differently based on imageType, but the default is to treat this as an OCI image. If this is not specified, the value is assumed to be that of the image field",
                    "type": "string"
                },
                "imageType":{
                    "description": "The type of image. If this is not specified, 'oci' is assumed",
                    "type": "string",
                    "default": "oci"
                },
                "digest":{
                    "description": "A cryptographic hash digest that can be used to validate the image. This may be interpreted differently based on imageType",
                    "type": "string"
                },
                "size": {
                    "description": "The image size in bytes",
                    "type":"integer"
                },
                "platform":{
                    "description": "The target platform",
                    "type": "object",
                    "properties": {
                        "architecture": {
                            "description": "The architecture of the image (i386, amd64, arm32, arm64,...)",
                            "type": "string"
                        },
                        "os": {
                            "description": "The operating system of the image (linux, windows, darwin,...)",
                            "type": "string"
                        }
                    }
                },
                "mediaType":{
                    "description": "The media type of the image",
                    "type": "string"
                }
            },
            "required": ["image"]
        },
        "credential": {
            "description": "Credential defines a particular credential, and where it should be placed in the invocation image",
            "type": "object",
            "properties": {
                "path":{
                    "description": "The path inside of the invocation image where credentials will be mounted",
                    "type": "string",
                    "pattern": "^(?!\/cnab\/app\/outputs)\/.+$"
                },
                "env":{
                    "description": "The environment variable name, such as MY_VALUE, into which the credential will be placed",
                    "type": "string"
                },
                
                "description": {
                    "description": "A user-friendly description of this credential",
                    "type": "string"
                },
                "required": {
                    "description": "Indicates whether this credential must be supplied. By default, credentials are optional.",
                    "type": "boolean",
                    "default": false
                }
            }
        },
        "parameter": {
            "description": "A parameter that can be passed into the invocation image",
            "type": "object",
            "properties": {
                "destination": {
                    "type": "object",
                    "properties": {
                        "path":{
                            "description": "The path inside of the invocation image where parameter data is mounted",
                            "type": "string",
                            "pattern": "^(?!\/cnab\/app\/outputs)\/.+$"
                        },
                        "env":{
                            "description": "The environment variable name, such as MY_VALUE, in which the parameter value is stored",
                            "type": "string"
                        }
                    }
                },
                "applyTo":{                    
                    "description": "An optional exhaustive list of actions handling this parameter",
                    "type":"array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": ["type", "destination"]
        },
        "output": {
            "description": "A value that is produced by running an invocation image",
            "type": "object",
            "properties": {
                "applyTo":{                    
                    "description": "An optional exhaustive list of actions producing this output",
                    "type":"array",
                    "items": {
                        "type": "string"
                    }
                },
                "path":{
                    "description": "The path inside of the invocation image where output will be written",
                    "type": "string",
                    "pattern": "^\/cnab\/app\/outputs\/.+$"
                }
                
            },
            "required": ["type", "path"]
        }
    },
    "additionalProperties": false
}

=== cnabio/cnab-spec/examples/101.02-bundle.json
{
  "credentials": {
    "hostkey": {
      "env": "HOST_KEY",
      "path": "/etc/hostkey.txt"
    },
    "image_token": {
      "env": "AZ_IMAGE_TOKEN"
    },
    "kubeconfig": {
      "path": "/home/.kube/config"
    }
  },
  "description": "An example 'thick' helloworld Cloud-Native Application Bundle",
  "images": {
    "my-microservice": {
      "description": "helloworld microservice",
      "digest": "sha256:bbbbbbbbbbbb...",
      "image": "technosophos/helloworld:0.1.2",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      },
      "size": 1337
    }
  },
  "invocationImages": [
    {
      "digest": "sha256:aaaaaaaaaaaa...",
      "image": "technosophos/helloworld:1.2.3",
      "imageType": "docker",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      },
      "size": 1337
    }
  ],
  "name": "helloworld",
  "outputs": {
    "clientCert" : {
      "contentEncoding" : "base64",
      "contentMediaType" : "application/x-x509-user-cert",
      "path" : "/cnab/app/outputs/clientCert",
      "sensitive" : true,
      "type" : "string"
    },
    "hostName" : {
        "applyTo" : ["install"],
        "description" : "the hostname produced installing the bundle",
        "path" : "/cnab/app/outputs/hostname",
        "type" : "string"
     },
    "port" : {
      "path" : "/cnab/app/outputs/port",
      "type" : "integer"
    }
  },
  "parameters": {
    "fields" : {
      "backend_port": {
        "default": 80,
        "description": "The port that the backend will listen on",
        "destination": {
          "path": "/path/to/backend_port"
        },
        "maximum": 10240,
        "minimum": 10,
        "type": "integer"
      }
    }
  },
  "schemaVersion": "v1.0.0-WD",
  "version": "1.0.0"
}

=== cnabio/cnab-spec/examples/101.01-bundle.json
{
  "credentials": {
    "hostkey": {
      "env": "HOST_KEY",
      "path": "/etc/hostkey.txt"
    }
  },
  "custom": {
    "com.example.backup-preferences": {
      "frequency": "daily"
    },
    "com.example.duffle-bag": {
      "icon": "https://example.com/icon.png",
      "iconType": "PNG"
    }
  },
  "description": "An example 'thin' helloworld Cloud-Native Application Bundle",
  "images": {
    "my-microservice": {
      "description": "my microservice",
      "digest": "sha256:aaaaaaaaaaaa...",
      "image": "technosophos/microservice:1.2.3"
    }
  },
  "invocationImages": [
    {
      "digest": "sha256:aaaaaaa...",
      "image": "technosophos/helloworld:0.1.0",
      "imageType": "docker"
    }
  ],
  "maintainers": [
    {
      "email": "matt.butcher@microsoft.com",
      "name": "Matt Butcher",
      "url": "https://example.com"
    }
  ],
  "name": "helloworld",
  "outputs": {
    "clientCert" : {
      "contentEncoding" : "base64",
      "contentMediaType" : "application/x-x509-user-cert",
      "path" : "/cnab/app/outputs/clientCert",
      "sensitive" : true,
      "type" : "string"
    },
    "hostName" : {
        "applyTo" : ["install"],
        "description" : "the hostname produced installing the bundle",
        "path" : "/cnab/app/outputs/hostname",
        "type" : "string"
     },
    "port" : {
      "path" : "/cnab/app/outputs/port",
      "type" : "integer"
    }
  },
  "parameters": {
    "fields" : {
      "backend_port": {
        "default": 80,
        "description": "The port that the back-end will listen on",
        "destination": {
          "env": "BACKEND_PORT"
        },
        "maximum": 10240,
        "minimum": 10,
        "type": "integer"
      }
    }
  },
  "schemaVersion": "v1.0.0-WD",
  "version": "0.1.2"
}
